#!/bin/bash

sites_path=~/ee4-sites
ee_installer_version=stable

if [ -f ~/.ee4/config.yml ]; then
    sed -e 's/:[^:\/\/]/=/g;s/$//g;s/ ^C/=/g' ~/.ee4/config.yml | tail -n +2  > config
    source config
    rm config
fi

EE_HOME=$HOME
mkdir $EE_HOME/.ee4 $sites_path > /dev/null 2>&1
touch $EE_HOME/.ee4/ee4.log > /dev/null 2>&1

USER_ID=`id -u`
GROUP_ID=`id -g`
DOCKER_ID=`getent group docker | cut -d: -f3`


base_status=$( docker inspect -f '{{.State.Running}}' ee4-base 2> /dev/null )
if [ "$?" -eq 0 ];then
    if [ "$base_status" = "false" ];then
        docker start ee4-base > /dev/null 2>&1
    fi
else
    docker run -dit --name ee4-base --privileged --net=host \
            -v ~/.ee4:$EE_HOME/.ee4 -v $sites_path:$sites_path \
            -v /var/run/docker.sock:/var/run/docker.sock:ro -v /etc/hosts:/etc/hosts:rw \
            -e HOST_HOME=$EE_HOME -e USER_ID=$USER_ID -e GROUP_ID=$GROUP_ID -e DOCKER_ID=$DOCKER_ID \
            --entrypoint "/bin/bash" easyengine/base:$ee_installer_version > /dev/null 2>&1
fi

docker exec -it ee4-base /usr/local/bin/ee4 "$@" --allow-root
